// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-pVserKncExpi8GzteVAkHWz_oc_Y2FM',
    appId: '1:540980899385:web:62659d5b9b271e94d527e8',
    messagingSenderId: '540980899385',
    projectId: 'haemophilia-physiotherapy-ai',
    authDomain: 'haemophilia-physiotherapy-ai.firebaseapp.com',
    storageBucket: 'haemophilia-physiotherapy-ai.firebasestorage.app',
    measurementId: 'G-LT1H0Y89XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzy8O2Pb7Jqk8qBHVDOUGufOjLlPI5zUE',
    appId: '1:540980899385:android:e0eb3a7a063973a9d527e8',
    messagingSenderId: '540980899385',
    projectId: 'haemophilia-physiotherapy-ai',
    storageBucket: 'haemophilia-physiotherapy-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCGRNAYiC1fNKa-ZY9aO_JBFkZ38j6MpE',
    appId: '1:540980899385:ios:ec188bd7033715aad527e8',
    messagingSenderId: '540980899385',
    projectId: 'haemophilia-physiotherapy-ai',
    storageBucket: 'haemophilia-physiotherapy-ai.firebasestorage.app',
    iosBundleId: 'com.example.haemophiliaApp',
  );
}
