import 'package:flutter/material.dart';
import '../../models/user_model.dart';
import '../../services/clinical_data_service.dart';
import '../patient/patient_history.dart';

class DoctorSessionDetail extends StatelessWidget {
  final String patientId; final UserModel patient; final AssessmentSession session;
  const DoctorSessionDetail({super.key,required this.patientId,required this.patient,required this.session});

  @override Widget build(BuildContext context){final rate=session.reps==0?0:(session.correctReps/session.reps)*100;return Scaffold(appBar:AppBar(title:const Text('Session review',style:TextStyle(fontWeight:FontWeight.w800))),body:ListView(padding:const EdgeInsets.fromLTRB(20,12,20,32),children:[
    Text(session.exercise,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w800)),const SizedBox(height:4),Text('${patient.name} • ${_date(session.date)}',style:TextStyle(color:Colors.grey.shade600)),const SizedBox(height:18),
    Wrap(spacing:10,runSpacing:10,children:[_Stat('Average score','${session.averageScore.toStringAsFixed(0)}/100'),_Stat('Correct reps','${session.correctReps}/${session.reps}'),_Stat('Success rate','${rate.toStringAsFixed(0)}%'),_Stat('Average ROM','${session.averageRom.toStringAsFixed(0)}°'),_Stat('Avg duration','${session.averageDuration.toStringAsFixed(1)}s'),_Stat('AI confidence','${session.averageConfidence.toStringAsFixed(1)}%')]),
    const SizedBox(height:26),const Text('Rep-by-rep review',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:12),
    ...session.repsData.asMap().entries.map((e)=>_RepReview(patientId:patientId,rep:e.value,number:e.key+1)),
  ]));}
  String _date(DateTime d){final x=d.toLocal();return '${x.day.toString().padLeft(2,'0')}/${x.month.toString().padLeft(2,'0')}/${x.year} • ${x.hour.toString().padLeft(2,'0')}:${x.minute.toString().padLeft(2,'0')}';}
}
class _RepReview extends StatefulWidget{final String patientId;final Map<String,dynamic> rep;final int number;const _RepReview({required this.patientId,required this.rep,required this.number});@override State<_RepReview> createState()=>_RepReviewState();}
class _RepReviewState extends State<_RepReview>{final _feedback=TextEditingController();bool _saving=false;@override void dispose(){_feedback.dispose();super.dispose();}
Future<void> _save()async{final text=_feedback.text.trim();if(text.isEmpty)return;setState(()=>_saving=true);try{await ClinicalDataService().addDoctorFeedback(patientId:widget.patientId,assessmentId:widget.rep['__docId']?.toString()??'',feedback:text);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Doctor feedback saved.')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Could not save feedback: $e')));}finally{if(mounted)setState(()=>_saving=false);}}
@override Widget build(BuildContext context){final d=widget.rep;final form=d['form']?.toString()??'Unknown';final incorrect=form.toLowerCase().contains('incorrect');final p=Theme.of(context).colorScheme.primary;final url=d['errorFrameUrl']?.toString()??'';final existing=d['doctorFeedback']?.toString()??'';if(existing.isNotEmpty&&_feedback.text.isEmpty)_feedback.text=existing;return Card(margin:const EdgeInsets.only(bottom:12),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Icon(incorrect?Icons.warning_amber_rounded:Icons.check_circle_outline,color:incorrect?Colors.red.shade600:p),const SizedBox(width:9),Expanded(child:Text('Rep ${widget.number} • $form',style:const TextStyle(fontWeight:FontWeight.w800,fontSize:16))),Text('${_num(d['score']).toStringAsFixed(0)}/100',style:TextStyle(color:incorrect?Colors.red.shade700:p,fontWeight:FontWeight.w800))]),const SizedBox(height:12),Row(children:[_M('ROM','${_num(d['rangeOfMotion']).toStringAsFixed(0)}°'),_M('SPEED',d['speed']?.toString()??'—'),_M('DURATION','${_num(d['duration']).toStringAsFixed(1)}s'),_M('AI','${_num(d['confidence']).toStringAsFixed(1)}%')]),if(incorrect&&url.isNotEmpty)...[const SizedBox(height:13),ClipRRect(borderRadius:BorderRadius.circular(14),child:GestureDetector(onTap:()=>showDialog(context:context,builder:(_)=>Dialog(child:InteractiveViewer(child:Image.network(url,errorBuilder:(_,__,___)=>const Padding(padding:EdgeInsets.all(30),child:Text('Error image unavailable.')))))),child:Image.network(url,height:190,width:double.infinity,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(height:120,color:Colors.grey.shade100,alignment:Alignment.center,child:const Text('Error image unavailable.')))))],if(incorrect)...[const SizedBox(height:13),Text(d['errorType']?.toString().replaceAll('_',' ').toUpperCase()??'',style:TextStyle(color:Colors.red.shade700,fontWeight:FontWeight.w800,fontSize:11)),const SizedBox(height:4),Text(d['feedback']?.toString()??'',style:TextStyle(color:Colors.grey.shade700,height:1.35)),const SizedBox(height:13),TextField(controller:_feedback,minLines:2,maxLines:4,decoration:const InputDecoration(labelText:'Doctor feedback',hintText:'Add guidance for this rep...')),const SizedBox(height:8),Align(alignment:Alignment.centerRight,child:FilledButton.icon(onPressed:_saving?null:_save,icon:const Icon(Icons.send_rounded,size:17),label:Text(_saving?'Saving...':'Send feedback'))),],if(!incorrect&&existing.isNotEmpty)...[const SizedBox(height:10),Text('Doctor feedback',style:TextStyle(fontWeight:FontWeight.w800,color:p)),const SizedBox(height:3),Text(existing,style:TextStyle(color:Colors.grey.shade700))]])));}
double _num(dynamic v)=>v is num?v.toDouble():double.tryParse(v?.toString()??'')??0;}
class _M extends StatelessWidget{final String l,v;const _M(this.l,this.v);@override Widget build(BuildContext c)=>Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(l,style:TextStyle(fontSize:9,color:Colors.grey.shade500,fontWeight:FontWeight.w800)),const SizedBox(height:3),Text(v,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w700,fontSize:11))]));}
class _Stat extends StatelessWidget{final String l,v;const _Stat(this.l,this.v);@override Widget build(BuildContext c)=>SizedBox(width:160,child:Card(child:Padding(padding:const EdgeInsets.all(15),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(v,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800)),const SizedBox(height:4),Text(l,style:TextStyle(color:Colors.grey.shade600,fontSize:11))]))));}
